networks:
  it_tickets_network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
      - "8080:8080"
    depends_on:
      - app
    networks:
      - it_tickets_network

  app:
    container_name: it-tickets-app
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www           # синхронизация проекта с хостом
      - ./_docker/app/entrypoint.sh:/usr/local/bin/entrypoint.sh
    depends_on:
      - db
    networks:
      - it_tickets_network
    environment:
      PGSQL_DB_CONNECTION: pgsql
      PGSQL_DB_HOST: db
      PGSQL_DB_PORT: 5432
      PGSQL_DB_DATABASE: it_tickets
      PGSQL_DB_USERNAME: postgres
      PGSQL_DB_PASSWORD: postgres

  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_DB: it_tickets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql
    networks:
      - it_tickets_network

volumes:
  pgdata:
